#!/usr/bin/env python3
"""Generate dist/agents/routing.json — every agent's tier/effort and its
resolved model/effort under every profile in agents/model-profiles.json,
for every harness (D-060).

bin/eef.js reads this file to apply `eef-install --profile <name>`. The
resolution logic (effort_shift, clamping, per-model effort ceilings) lives
only in lib_agents.resolve_model(); the installer just looks values up
here, so the Python exporters and the Node installer can never disagree
about what a profile means.

Usage:
    python scripts/export_agents_routing.py            # write dist/agents/routing.json
    python scripts/export_agents_routing.py --check     # exit 1 if stale
"""
import argparse
import json
import sys

from lib_agents import REPO_ROOT, load_agents, load_profiles, resolve_model

DEST = REPO_ROOT / "dist" / "agents" / "routing.json"


def build() -> str:
    profiles = load_profiles()
    agents = {}
    for agent in load_agents():
        resolved = {}
        for profile in profiles["profiles"]:
            resolved[profile] = {}
            for harness in profiles["harnesses"]:
                model, effort = resolve_model(agent, harness, profiles, profile)
                resolved[profile][harness] = {"model": model, "effort": effort}
        agents[agent.name] = {"tier": agent.tier, "effort": agent.effort, "profiles": resolved}
    routing = {
        "_doc": "Generated by scripts/export_agents_routing.py from agents/model-profiles.json — do not edit.",
        "verified": profiles["verified"],
        "default_profile": profiles["default_profile"],
        "profiles": list(profiles["profiles"]),
        "tiers": profiles["tiers"],
        # Only for models a consumer substitutes with --models; every
        # profile value below is already clamped by resolve_model().
        "effort_levels": profiles["effort_levels"],
        "model_limits": profiles["model_limits"],
        "agents": agents,
    }
    return json.dumps(routing, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if routing.json is stale instead of writing it")
    args = parser.parse_args()

    content = build()
    current = DEST.read_text(encoding="utf-8", newline=None) if DEST.exists() else None
    if current == content:
        print("dist/agents/routing.json is in sync.")
        return 0
    if args.check:
        print("STALE: dist/agents/routing.json\n\nRun: python scripts/export_agents_routing.py")
        return 1
    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text(content, encoding="utf-8", newline="\n")
    print("Wrote: dist/agents/routing.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
